config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :map_points
  # get "home/index"
  get '/map', to: 'map#index'
  get '/map/demo', to: 'map#demo'
  get "home/log"
  root "home#log"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/map_point.rb
class MapPoint < ApplicationRecord
    belongs_to :user
    validates :country, presence: true
    validates :city, inclusion: { in: ->(record) { record.cities } }
    validates :city, presence: { if: ->(record) { record.cities.present? } }
    def countries
        CS.countries.with_indifferent_access
    end
    def test_text
        CS.cities('82', 'DK')[0]
    end
    def cities
        states = CS.states(country)
        all_cities = states.keys.flat_map { |state| CS.cities(state, country) }
        (all_cities || []).sort
    end
    def country_label
        if country.length == 2
            countries[country]
        else
            country
        end
    end
    def latitude
        result = Geocoder.search(city).first
        if result && result.coordinates
            result.coordinates[0]
        else
            ''
        end
    end
    def longitude
        result = Geocoder.search(city).first
        if result && result.coordinates
            result.coordinates[1]
        else
            ''
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :map_points
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def map
  end
  def log
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  before_action :authenticate_user!, only: :index
  
    def index
      @map_points = current_user.map_points.order(start_date: :asc)
    end

    def demo
      @map_points_2 = MapPoint.where(user_id: 1).order(start_date: :asc)
    end

end

app/controllers/map_points_controller.rb
class MapPointsController < ApplicationController
  before_action :set_map_point, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /map_points or /map_points.json
  def index
    @map_points = MapPoint.all
    @map_points_sorted = MapPoint.all.order(start_date: :asc)
  end

  # GET /map_points/1 or /map_points/1.json
  def show
  end

  # GET /map_points/new
  def new
    #@map_point = MapPoint.new
    @map_point = current_user.map_points.build map_point_params
  end

  # GET /map_points/1/edit
  def edit
  end

  # POST /map_points or /map_points.json
  def create
    #@map_point = MapPoint.new(map_point_params)
    @map_point = current_user.map_points.build(map_point_params)

    respond_to do |format|
      if @map_point.save
        format.html { redirect_to @map_point, notice: "Map point was successfully created." }
        format.json { render :show, status: :created, location: @map_point }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @map_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /map_points/1 or /map_points/1.json
  def update
    respond_to do |format|
      if @map_point.update(map_point_params)
        format.html { redirect_to @map_point, notice: "Map point was successfully updated." }
        format.json { render :show, status: :ok, location: @map_point }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @map_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /map_points/1 or /map_points/1.json
  def destroy
    @map_point.destroy!

    respond_to do |format|
      format.html { redirect_to map_points_path, status: :see_other, notice: "Map point was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @map_point = current_user.map_points.find_by(id: params[:id])
    redirect_to map_points_path, notice: "Not Authorized To Edit This Point" if @map_point.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map_point
      @map_point = MapPoint.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def map_point_params
      #params.expect(map_point: [ :country, :city, :latitude, :longitude, :start_date, :end_date, :short_description, :long_description, :user_id ])
      params.fetch(:map_point, {}).permit(:country, :city, :latitude, :longitude, :start_date, :end_date, :short_description, :long_description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_points_helper.rb
module MapPointsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <img src="<%= asset_path('navbar_logo.png') %>" alt="Bootstrap" width="33" height="33">
    &nbsp;&nbsp;<%= link_to 'Veast', root_path, class:"navbar-brand mb-0 h1" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Demo", map_demo_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Map", map_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Points", map_points_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <% link_to "Log", home_log_path, class:"nav-link" %>
        </li>

        </li>
        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link" %>
          </li>
        
        <% else %>
          <li class="nav-item">
            <%= link_to "Register", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class:"nav-link" %>
          </li>

        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Hello World!</h1>
<p>This is my first rails web page</p>

app/views/home/log.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <% content_for :head do %>
        <%= stylesheet_link_tag 'log' %>
    <% end %>
</head>
<body>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/typed.js/1.1.1/typed.min.js'></script>
    <div data-controller="log" class="canvas-container">
        </br></br></br>
            <section id="terminal" draggable="true">
                <div id="terminal-container" data-log-target="terminal">
                    <div class="terminal">
                        <div class="window-title draggable-handle">
                            <div class="win-buttons">
                                <a id="close" class="button" href="#"></a>
                                <a id="min" class="button" href="#"></a>
                                <a id="max" class="button" href="#"></a>
                            </div>
                            <span class="title">.zsh</span>
                        </div>
                            <div class="message">
                                <span class='prompt'><span class='user'>rails</span><span class="at">@</span><span
                                        class="path">veast</span>><span
                                        class="caret">$</span></span>
                                <% if current_user %>
                                    <span class="logtyped" id="current-user" data-user-email="<%= current_user.email %>"></span>
                                <% else %>
                                    <span class="typed"></span>
                                <% end %>
                            </div>
                    </div>
                </div>
            </section>
    </div>
</body>
</html>

app/views/home/map.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Leaflet Map Implementation</title>
    <link rel="stylesheet"  href="https://unpkg.com/[email protected]/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="">
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css" />
    <style>
        #map-container {
            height: 600px;
            width: 100%;
            margin: 20px auto;
            border-radius: 8px;
            box-shadow: 0 2px 6px rgba(0,0,0,0.3);
        }
    </style>
</head>
<body>
    <div id="map-container"
        data-controller="map"
        data-map-center-value="[46.204391, 6.143158]"
        data-map-zoom-value="3"
        data-pop-img="<%= asset_path('pop/zombie.jpeg') %>"
        class="leaflet-map-container"
        style="height: 600px; width: 100%; margin: 20px auto; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,0.3);">
    </div>

    <!-- Leaflet JS loaded after CSS -->
    <script src="https://unpkg.com/[email protected]/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <script src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
    <script src="https://unpkg.com/@elfalem/leaflet-curve@0.9.0/dist/leaflet.curve.js"></script>
    <script src="https://unpkg.com/@tweenjs/tween.js@18.6.4/dist/tween.umd.js"></script>
</body>
</html>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render 'home/header'%>
    <div class="container">
    </br>

    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>

      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

app/views/map/demo.html.erb
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Leaflet Map Implementation</title>
    <link rel="stylesheet"  href="https://unpkg.com/[email protected]/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="">
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css" />
</head>
<body>
    <div id="map-container"
        data-controller="map"
        data-map-center-value="[46.204391, 6.143158]"
        data-map-zoom-value="3"
        data-pop-img="<%= asset_path('pop/zombie.jpeg') %>"
        data-map-points="<%= @map_points_2.to_json %>"
        class="leaflet-map-container"
        style="height: 600px; width: 100%; margin: 8px auto; margin-bottom: 22px; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,0.3);">
    </div>

    <%= link_to "New Map Point", new_map_point_path, class: "btn btn-secondary btn-sm" %>

    <%= link_to 'Go to Map Points', map_points_path, class: "btn btn-outline-dark btn-sm float-end" %>

    <!-- Leaflet JS loaded after CSS -->
    <script src="https://unpkg.com/[email protected]/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <script src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
    <script src="https://unpkg.com/@elfalem/leaflet-curve@0.9.0/dist/leaflet.curve.js"></script>
    <script src="https://unpkg.com/@tweenjs/tween.js@18.6.4/dist/tween.umd.js"></script>

</body>
</html>

app/views/map/index.html.erb
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Leaflet Map Implementation</title>
    <link rel="stylesheet"  href="https://unpkg.com/[email protected]/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="">
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.4.1/dist/MarkerCluster.Default.css" />
</head>
<body>
    <div id="map-container"
        data-controller="map"
        data-map-center-value="[46.204391, 6.143158]"
        data-map-zoom-value="3"
        data-pop-img="<%= asset_path('pop/zombie.jpeg') %>"
        data-map-points="<%= @map_points.to_json %>"
        class="leaflet-map-container"
        style="height: 600px; width: 100%; margin: 8px auto; margin-bottom: 22px; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,0.3);">
    </div>

    <%= link_to "New Map Point", new_map_point_path, class: "btn btn-secondary btn-sm" %>

    <%= link_to 'Go to Map Points', map_points_path, class: "btn btn-outline-dark btn-sm float-end" %>

    <!-- Leaflet JS loaded after CSS -->
    <script src="https://unpkg.com/[email protected]/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <script src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
    <script src="https://unpkg.com/@elfalem/leaflet-curve@0.9.0/dist/leaflet.curve.js"></script>
    <script src="https://unpkg.com/@tweenjs/tween.js@18.6.4/dist/tween.umd.js"></script>

</body>
</html>

app/views/map_points/_form.html.erb
<%= form_with(model: map_point, data: {controller: "form-reset"}) do |form| %>
  <% if map_point.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(map_point.errors.count, "error") %> prohibited this map_point from being saved:</h2>

      <ul>
        <% map_point.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= turbo_frame_tag :cs_select do %>
    <div data-controller="form-element">
      <%= form.button "Validate", formaction: new_map_point_path, formmethod: :get, data: { form_element_target: "remoteBtn", turbo_frame: :cs_select } %>
      <div class="mb-3">
        <%= form.label :country, style: "display: block" %>
        <%= form.select :country, map_point.countries.invert.sort, { prompt: "Select a Country" }, { class: "form-select", data: {action: "change->form-element#autosubmit"} } %>
      </div>
      <%= map_point.test_text %>
      <div class="mb-3">
        <%= form.label :city, style: "display: block" %>
        <%= form.select :city, map_point.cities, { prompt: "Select a City" }, { class: "form-select", data: {action: "change->form-element#autosubmit" } } %>
      </div>
    </div>
  
    <h8>Coordinates</h8>
    <div class="mb-3">
      <% form.label :latitude, style: "display: block" %>
      <%= form.number_field :latitude, step: "any", class: "form-control", placeholder: "Latitude", value: @map_point.latitude %>
    </div>
    <div class="mb-3">
      <% form.label :longitude, style: "display: block" %>
      <%= form.number_field :longitude, step: "any", class: "form-control", placeholder: "Longitude", value: @map_point.longitude %>
    </div>
  <% end %>
  
  <div class="mb-3">
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date, class:"form-control" %>
  </div>

  <div class="mb-3">
    <% form.label :short_description, style: "display: block" %>
    <%= form.text_field :short_description, class:"form-control", placeholder:"Short Description" %>
  </div>

  <div class="mb-3">
    <% form.label :long_description, style: "display: block" %>
    <%= form.text_field :long_description, class:"form-control", placeholder:"Long Description" %>
  </div>

  <div class="mb-3">
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :map_point_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>
  <br/>
  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/map_points/_map_point.html.erb
<div id="<%= dom_id map_point %>">
  <p>
    <strong>Country:</strong>
    <%= map_point.country_label %>
  </p>

  <p>
    <strong>City:</strong>
    <%= map_point.city %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= map_point.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= map_point.longitude %>
  </p>

  <p>
    <strong>Start Date:</strong>
    <%= map_point.start_date %>
  </p>

  <p>
    <strong>End Date:</strong>
    <%= map_point.end_date %>
  </p>

  <p>
    <strong>Short Description:</strong>
    <%= map_point.short_description %>
  </p>

  <p>
    <strong>Long Description:</strong>
    <%= map_point.long_description %>
  </p>

</div>

app/views/map_points/edit.html.erb
<h1>Editing Map Points</h1>
<br/>
<%= render 'form', map_point: @map_point %>

<br/>
<%= link_to 'Show', @map_point, class:"btn btn-primary" %>
&nbsp;&nbsp;
<%= link_to 'Delete', @map_point, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
&nbsp;&nbsp;
<%= link_to 'Back to Map Points', map_points_path, class:"btn btn-outline-dark" %>

app/views/map_points/index.html.erb
<% content_for :title, "Map points" %>

<table class="table table-hover">
    <thead class="table">
      <tr>
        <th>City</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>User Id</th>
        <th> </th>
        <th> </th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      <% @map_points_sorted.each do |map_point| %>
        <% if map_point.user == current_user %>
          <tr>
            <td><%= link_to "#{map_point.city}, #{map_point.country_label}", map_point, class: "point-name-link" %></td>
            <td><%= map_point.latitude %></td>
            <td><%= map_point.longitude %></td>
            <td><%= map_point.start_date %></td>
            <td><%= map_point.end_date %></td>
            <td><%= map_point.user_id %></td>
            <td><%= link_to 'Edit', edit_map_point_path(map_point), class: "btn btn-outline-primary btn-sm" %></td>
            <td><%= link_to 'Delete', map_point, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
</table>

<%= link_to "New map point", new_map_point_path, class: "btn btn-secondary" %>

app/views/map_points/new.html.erb
<% content_for :title, "New map point" %>

<h1>New map point</h1>
<br/>
<%= render "form", map_point: @map_point %>

<br/>

<%= link_to 'Back to Map Points', map_points_path, class:"btn btn-outline-dark" %>

app/views/map_points/show.html.erb
<div class="p-5 mb-4 bg-body-tertiary rounded-3">
  <div class="container-fluid">
    <h1 class="display-5 fw-bold"><%= @map_point.city %>, <%= @map_point.country_label %></h1>
    
    <strong>Latitude: </strong><%= @map_point.latitude %> &nbsp;|&nbsp;
    <strong>Longitude: </strong><%= @map_point.longitude %>
    </br>
    <strong>Start Date: </strong><%= @map_point.start_date %> &nbsp;|&nbsp;  
    <strong>End Date: </strong><%= @map_point.end_date %>

    <p class="col-md-8 fs-5"><%= @map_point.short_description %></p>
    <div>
      <%= link_to "Back to Map", map_path, class: "btn btn-outline-dark" %>&nbsp;&nbsp;
      <%= link_to "Back to Points", map_points_path, class: "btn btn-outline-dark" %>
      </br></br>
      <%= link_to "Edit", edit_map_point_path(@map_point), class: "btn btn-outline-primary" %>&nbsp;&nbsp;
      <%= link_to 'Delete', @map_point, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
    </div>

  </div>
</div>